#!/bin/sh
d=`dirname $0`
d=`realpath $d`
echo $d
export PATH=$d/bin:$PATH

#hopdr-check-runner

#cargo run --features stat --features "no_simplify_by_finding_eq" --bin check -- --do-format --print-check-log --input $@
cargo run --features "no_simplify_by_finding_eq" --bin check -- --do-format --print-check-log --input $@
